name: Test contracts and library

on:
  push:
    branches: 
    - master
    paths-ignore:
      - '**.md'
  pull_request:
    # branches:
    # - master
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: make ts-deps server-deps
      
    - name: Build
      run: make lib server

    - name: Install dev dependencies
      run: make ts-dev-deps server-dev-deps
      
    - name: Test on Hangzhou
      run: make test
      env:
        FINP2P_SANDBOX_NETWORK: hangzhou

    - name: Test on Ithaca
      run: make test
      env:
        FINP2P_SANDBOX_NETWORK: ithaca
