name: Test contracts and library

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: make ts-dev-deps server-dev-deps
      
    - name: Build
      run: make lib server
      
    - name: Test
      run: make test
